version: 2
updates:
- package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:30"
  open-pull-requests-limit: 20
- package-ecosystem: github-actions
  directory: "/"
  schedule:
     interval: daily
  open-pull-requests-limit: 10
