version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - ">= 5.a, < 6"
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - ">= 6.a, < 7"
