CREATE TABLE "STATISTIKK_KO"
(
    "ID"                    number(19)                             NOT NULL,
    "OPPGAVE_ID"            NUMBER(19, 0)                          NOT NULL,
    "OPPGAVE_FILTRERING_ID" NUMBER(19, 0)                          NOT NULL,
    "BEHANDLING_TYPE"       VARCHAR2(100 CHAR)                     NOT NULL,
    "HENDELSE"              VARCHAR(20 CHAR)                       NOT NULL,
    "VERSJON"               NUMBER(19, 0)     DEFAULT 0,
    "OPPRETTET_AV"          VARCHAR2(20 CHAR) DEFAULT 'VL'         NOT NULL ENABLE,
    "OPPRETTET_TID"         TIMESTAMP(3)      DEFAULT systimestamp NOT NULL ENABLE,
    "ENDRET_AV"             VARCHAR2(20 CHAR),
    "ENDRET_TID"            TIMESTAMP(3)
);

COMMENT ON COLUMN STATISTIKK_KO.ID IS 'Primary Key';
COMMENT ON COLUMN STATISTIKK_KO.OPPGAVE_ID IS 'Refererer til oppgave';
COMMENT ON COLUMN STATISTIKK_KO.OPPGAVE_FILTRERING_ID IS 'Refererer til oppgavekø';
COMMENT ON COLUMN STATISTIKK_KO.BEHANDLING_TYPE IS 'Behandlingtype';
COMMENT ON COLUMN STATISTIKK_KO.HENDELSE IS 'Hendelsetype';
COMMENT ON COLUMN STATISTIKK_KO.VERSJON IS 'angir versjon for optimistisk låsing hvor aktuelt';
COMMENT ON COLUMN STATISTIKK_KO.OPPRETTET_AV IS 'Opprettet av';
COMMENT ON COLUMN STATISTIKK_KO.OPPRETTET_TID IS 'Tidspunkt opprettet';
COMMENT ON COLUMN STATISTIKK_KO.ENDRET_AV IS 'Endret av';
COMMENT ON COLUMN STATISTIKK_KO.ENDRET_TID IS 'Timestamp endring';
COMMENT ON TABLE STATISTIKK_KO IS 'Data om endringer i oppgavebeholdning';

CREATE SEQUENCE "SEQ_STATISTIKK_KO" MINVALUE 1000 INCREMENT BY 50 START WITH 1000 NOCACHE NOCYCLE;

ALTER TABLE STATISTIKK_KO
    ADD CONSTRAINT PK_STATISTIKK_KO PRIMARY KEY (ID);

CREATE INDEX "IDX_KOSTAT_OPPR" ON "STATISTIKK_KO" ("OPPRETTET_TID");

