CREATE TABLE "RISIKOKLASSIFISERING"
(
    "BEHANDLING_ID"     RAW(16)                                 NOT NULL ENABLE,
    "OPPRETTET_AV"      VARCHAR2(20 CHAR)  DEFAULT 'VL'         NOT NULL ENABLE,
    "OPPRETTET_TID"     TIMESTAMP(3)       DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "ENDRET_AV"         VARCHAR2(20 CHAR),
    "ENDRET_TID"        TIMESTAMP(3),
    "ID"                NUMBER(19, 0)                           NOT NULL ENABLE,
    "KONTROLL_RESULTAT" VARCHAR2(100 CHAR) DEFAULT ('-')        NOT NULL ENABLE,
    "ERAKTIV"           VARCHAR2(1 CHAR)   DEFAULT ('N')        NOT NULL ENABLE
);
ALTER TABLE "RISIKOKLASSIFISERING"
    ADD CONSTRAINT "PK_RISIKOKLASSIFISERING" PRIMARY KEY ("ID")
        USING INDEX ENABLE;
ALTER TABLE "RISIKOKLASSIFISERING"
    ADD CHECK (erAktiv IN ('J', 'N')) ENABLE;
CREATE SEQUENCE SEQ_RISIKOKLASSIFISERING MINVALUE 1000 INCREMENT BY 50 START WITH 1000 NOCACHE ORDER NOCYCLE;

COMMENT ON TABLE RISIKOKLASSIFISERING IS 'Tabell for å holde på risikoklassifisering';
COMMENT ON COLUMN RISIKOKLASSIFISERING.BEHANDLING_ID IS 'BehandlingId';
COMMENT ON COLUMN RISIKOKLASSIFISERING.ERAKTIV IS 'Er risikoklassifisering aktiv';
COMMENT ON COLUMN RISIKOKLASSIFISERING.KONTROLL_RESULTAT IS 'Resultat av risikoklassifisering';

INSERT INTO PROSESS_TASK_TYPE (KODE, NAVN, FEIL_MAKS_FORSOEK, FEIL_SEK_MELLOM_FORSOEK, FEILHANDTERING_ALGORITME,
                               BESKRIVELSE, OPPRETTET_AV, OPPRETTET_TID, ENDRET_AV, ENDRET_TID, CRON_EXPRESSION)
VALUES ('risiko.klassifisering.resultat', 'Korrigerer endretdato', 3, 30, 'DEFAULT',
        'Korrigerer endretdato etter kafkaproblemer', 'VL', CURRENT_TIMESTAMP, null, null, null);

