CREATE TABLE "DRIFTSMELDING"
(
    ID            number(19) not null,
    MELDING       varchar2(1500 CHAR),
    AKTIV_FRA     TIMESTAMP(3),
    AKTIV_TIL     TIMESTAMP(3),
    VERSJON       NUMBER(19, 0)     DEFAULT 0,
    OPPRETTET_AV  VARCHAR2(20 CHAR) DEFAULT 'VL',
    OPPRETTET_TID TIMESTAMP(3)      DEFAULT systimestamp,
    ENDRET_AV     VARCHAR2(20 CHAR),
    ENDRET_TID    TIMESTAMP(3)
);

COMMENT ON COLUMN DRIFTSMELDING.ID IS 'Primary Key';
COMMENT ON COLUMN DRIFTSMELDING.MELDING IS 'Body tekst driftsmelding';
COMMENT ON COLUMN DRIFTSMELDING.AKTIV_FRA IS 'Driftsmelding er aktiv fra';
COMMENT ON COLUMN DRIFTSMELDING.AKTIV_TIL IS 'Driftsmelding er aktiv til';
COMMENT ON COLUMN DRIFTSMELDING.VERSJON IS 'angir versjon for optimistisk låsing';
COMMENT ON COLUMN DRIFTSMELDING.OPPRETTET_AV IS 'Driftsmelding opprettet av';
COMMENT ON COLUMN DRIFTSMELDING.OPPRETTET_TID IS 'Tidspunkt da driftsmeldingen ble opprettet';
COMMENT ON COLUMN DRIFTSMELDING.ENDRET_AV IS 'Driftsmelding endret av';
COMMENT ON COLUMN DRIFTSMELDING.ENDRET_TID IS 'Timestamp endring';
COMMENT ON TABLE DRIFTSMELDING IS 'Driftsmeldinger til saksbehandlere';

CREATE SEQUENCE "SEQ_DRIFTSMELDING" MINVALUE 1000 INCREMENT BY 50 START WITH 1000 NOCACHE NOCYCLE;

ALTER TABLE DRIFTSMELDING
    ADD CONSTRAINT PK_DRIFTSMELDING PRIMARY KEY (ID);

CREATE INDEX "IDX_DRIFTSMELDING_AKTIVTIL" ON "DRIFTSMELDING" ("AKTIV_TIL");
