kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fplos
  namespace: {{namespace}}
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  ingresses:
{{#each ingresses as |url|}}
   - {{url}}
{{/each}}
  liveness:
    path: /fplos/internal/isAlive
    port: 8080
    initialDelay: 30
    periodSeconds: 10
    failureThreshold: 27
    timeout: 5
  port: 8080
  preStopHookPath: /fplos/internal/preStop
  readiness:
    path: /fplos/internal/isReady
    port: 8080
    initialDelay: 30
    periodSeconds: 10
    failureThreshold: 27
    timeout: 5
  replicas:
    min: {{minReplica}}
    max: {{maxReplica}}
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{oraclecredskv}}
        mountPath: /var/run/secrets/nais.io/defaultDS
      - kvPath: {{oracleconfigkv}}
        mountPath: /var/run/secrets/nais.io/defaultDSconfig
      - kvPath: {{serviceuserkv}}
        mountPath: /var/run/secrets/nais.io/srvfplos
      - kvPath: {{ldapuserkv}}
        mountPath: /var/run/secrets/nais.io/ldap
      - kvPath: /kv/{{cluster}}/fss/fplos/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault
  env:
{{#each env}}
   - name: {{@key}}
     value: "{{this}}"
  {{/each}}
