CREATE TABLE FILTRERING_YTELSE_TYPE (
   ID NUMBER(19,0) NOT NULL
  ,OPPGAVE_FILTRERING_ID NUMBER(19,0) NOT NULL
  ,FAGSAK_YTELSE_TYPE VARCHAR2(100 CHAR) NOT NULL
  ,KL_FAGSAK_YTELSE_TYPE VARCHAR2(100 CHAR) AS ('FAGSAK_YTELSE') NOT NULL,
   versjon            NUMBER(19, 0) DEFAULT 0           NOT NULL,
   opprettet_av       VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
   opprettet_tid      TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
   endret_av          VARCHAR2(20 CHAR),
   endret_tid         TIMESTAMP(3)
  ,CONSTRAINT PK_FILTRERING_YTELSE_TYPE PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_FILTRERING_YTELSE_TYPE MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_FILTR_YTELSE_TYPE_1 on FILTRERING_YTELSE_TYPE(OPPGAVE_FILTRERING_ID,FAGSAK_YTELSE_TYPE);

CREATE INDEX IDX_FILTR_YTELSE_TYPE_2 on FILTRERING_YTELSE_TYPE(FAGSAK_YTELSE_TYPE);

ALTER TABLE FILTRERING_YTELSE_TYPE ADD CONSTRAINT FK_FILTRERING_YTELSE_TYPE_1
  FOREIGN KEY (KL_FAGSAK_YTELSE_TYPE, FAGSAK_YTELSE_TYPE) REFERENCES KODELISTE (kodeverk, kode);

COMMENT ON TABLE FILTRERING_YTELSE_TYPE is 'Tabell inneholder filtreringer på behandlingType';

COMMENT ON COLUMN FILTRERING_YTELSE_TYPE.ID IS 'PK';
COMMENT ON COLUMN FILTRERING_YTELSE_TYPE.OPPGAVE_FILTRERING_ID IS 'Oppgavefiltrering som filtreringen hører til';
COMMENT ON COLUMN FILTRERING_YTELSE_TYPE.FAGSAK_YTELSE_TYPE IS 'Koden ytelsetypen skal filtreres på';
COMMENT ON COLUMN FILTRERING_YTELSE_TYPE.KL_FAGSAK_YTELSE_TYPE IS 'Kodeverk ytelsetype';