CREATE TABLE FILTRERING_BEHANDLING_TYPE (
   ID NUMBER(19,0) NOT NULL
  ,OPPGAVE_FILTRERING_ID NUMBER(19,0) NOT NULL
  ,BEHANDLING_TYPE VARCHAR2(100 CHAR) NOT NULL
  ,KL_BEHANDLING_TYPE VARCHAR2(100 CHAR) AS ('BEHANDLING_TYPE') NOT NULL,
   versjon            NUMBER(19, 0) DEFAULT 0           NOT NULL,
   opprettet_av       VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
   opprettet_tid      TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
   endret_av          VARCHAR2(20 CHAR),
   endret_tid         TIMESTAMP(3)
  ,CONSTRAINT PK_FILTR_BEHANDLING_TYPE PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_FILTR_BEHANDLING_TYPE MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_FILTR_BEHANDLING_TYPE_1 on FILTRERING_BEHANDLING_TYPE(OPPGAVE_FILTRERING_ID,BEHANDLING_TYPE);
CREATE INDEX IDX_FILTR_BEHANDLING_TYPE_2 on FILTRERING_BEHANDLING_TYPE(BEHANDLING_TYPE);

ALTER TABLE FILTRERING_BEHANDLING_TYPE ADD CONSTRAINT FK_FILTR_BEHANDLING_TYPE_1
FOREIGN KEY (KL_BEHANDLING_TYPE, BEHANDLING_TYPE) REFERENCES KODELISTE (kodeverk, kode);

COMMENT ON TABLE FILTRERING_BEHANDLING_TYPE is 'Tabell inneholder filtreringer på behandlingType';

COMMENT ON COLUMN FILTRERING_BEHANDLING_TYPE.ID IS 'PK';
COMMENT ON COLUMN FILTRERING_BEHANDLING_TYPE.OPPGAVE_FILTRERING_ID IS 'Listen filtreringen hører til';
COMMENT ON COLUMN FILTRERING_BEHANDLING_TYPE.BEHANDLING_TYPE IS 'Koden behandlingstypen skal filtreres på';
COMMENT ON COLUMN FILTRERING_BEHANDLING_TYPE.KL_BEHANDLING_TYPE IS 'Kodeverk behandlingstype';