INSERT INTO KODEVERK (KODE, KODEVERK_EIER, NAVN, BESKRIVELSE, OPPRETTET_AV, SAMMENSATT)
VALUES ('ANDRE_KRITERIER', 'VLLOS', 'ANDRE_KRITERIER', 'Internt kodeverk for andre kriterier for filtrering.','VLLOS', 'N');

INSERT INTO KODELISTE (id, kodeverk, kode, gyldig_fom)
VALUES  (seq_kodeliste.nextval, 'ANDRE_KRITERIER', 'TIL_BESLUTTER', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE (id, kodeverk, kode, gyldig_fom)
VALUES  (seq_kodeliste.nextval, 'ANDRE_KRITERIER', 'PAPIRSOKNAD', to_date('2000-01-01', 'YYYY-MM-DD'));


INSERT INTO KODELISTE_NAVN_I18N (id, kl_kodeverk, kl_kode, sprak, navn)
VALUES  (seq_kodeliste.nextval, 'ANDRE_KRITERIER', 'TIL_BESLUTTER', 'NB', 'Til beslutter');

INSERT INTO KODELISTE_NAVN_I18N (id, kl_kodeverk, kl_kode, sprak, navn)
VALUES  (seq_kodeliste.nextval, 'ANDRE_KRITERIER', 'PAPIRSOKNAD', 'NB', 'Registrer papirsøknad');


CREATE TABLE FILTRERING_ANDRE_KRITERIER (
   ID NUMBER(19,0) NOT NULL
  ,OPPGAVE_FILTRERING_ID NUMBER(19,0) NOT NULL
  ,ANDRE_KRITERIER_TYPE VARCHAR2(100 CHAR) NOT NULL
  ,KL_ANDRE_KRITERIER_TYPE VARCHAR2(100 CHAR) AS ('ANDRE_KRITERIER') NOT NULL,
   versjon            NUMBER(19, 0) DEFAULT 0           NOT NULL,
   opprettet_av       VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
   opprettet_tid      TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
   endret_av          VARCHAR2(20 CHAR),
   endret_tid         TIMESTAMP(3)
  ,CONSTRAINT PK_FILTRERING_ANDRE_KRITERIER PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_FILTRERING_ANDRE_KRIT MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_FILTRERING_ANDRE_KRIT_1 on FILTRERING_ANDRE_KRITERIER(OPPGAVE_FILTRERING_ID,ANDRE_KRITERIER_TYPE);

CREATE INDEX IDX_FILTRERING_ANDRE_KRIT_2 on FILTRERING_ANDRE_KRITERIER(ANDRE_KRITERIER_TYPE);

ALTER TABLE FILTRERING_ANDRE_KRITERIER ADD CONSTRAINT FK_FILTRERING_ANDRE_KRIT_1
FOREIGN KEY (KL_ANDRE_KRITERIER_TYPE, ANDRE_KRITERIER_TYPE) REFERENCES KODELISTE (kodeverk, kode);

COMMENT ON TABLE FILTRERING_ANDRE_KRITERIER is 'Tabell inneholder filtreringer for andre kriterier';

COMMENT ON COLUMN FILTRERING_ANDRE_KRITERIER.ID IS 'PK';
COMMENT ON COLUMN FILTRERING_ANDRE_KRITERIER.OPPGAVE_FILTRERING_ID IS 'Oppgavefiltrering som filtreringen hører til';
COMMENT ON COLUMN FILTRERING_ANDRE_KRITERIER.ANDRE_KRITERIER_TYPE IS 'Kode for de andre kriteriene oppgavene skal filtreres på';
COMMENT ON COLUMN FILTRERING_ANDRE_KRITERIER.KL_ANDRE_KRITERIER_TYPE IS 'Kodeverk andre kriterier';


CREATE TABLE OPPGAVE_EGENSKAP (
   ID NUMBER(19,0) NOT NULL
  ,OPPGAVE_ID NUMBER(19,0) NOT NULL
  ,ANDRE_KRITERIER_TYPE VARCHAR2(100 CHAR) NOT NULL
  ,KL_ANDRE_KRITERIER_TYPE VARCHAR2(100 CHAR) AS ('ANDRE_KRITERIER') NOT NULL,
   versjon            NUMBER(19, 0) DEFAULT 0           NOT NULL,
   opprettet_av       VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
   opprettet_tid      TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
   endret_av          VARCHAR2(20 CHAR),
   endret_tid         TIMESTAMP(3)
  ,CONSTRAINT PK_OPPGAVE_EGENSKAP PRIMARY KEY (ID)
);


CREATE SEQUENCE SEQ_OPPGAVE_EGENSKAP MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_OPPGAVE_EGENSKAP_1 on OPPGAVE_EGENSKAP(OPPGAVE_ID,ANDRE_KRITERIER_TYPE);

CREATE INDEX IDX_OPPGAVE_EGENSKAP_2 on OPPGAVE_EGENSKAP(ANDRE_KRITERIER_TYPE);

ALTER TABLE OPPGAVE_EGENSKAP ADD CONSTRAINT FK_OPPGAVE_EGENSKAP_1
FOREIGN KEY (KL_ANDRE_KRITERIER_TYPE, ANDRE_KRITERIER_TYPE) REFERENCES KODELISTE (kodeverk, kode);

COMMENT ON TABLE OPPGAVE_EGENSKAP is 'Tabell inneholder filtreringer for andre kriterier';

COMMENT ON COLUMN OPPGAVE_EGENSKAP.ID IS 'PK';
COMMENT ON COLUMN OPPGAVE_EGENSKAP.OPPGAVE_ID IS 'Oppgave egenskapen hører til';
COMMENT ON COLUMN OPPGAVE_EGENSKAP.ANDRE_KRITERIER_TYPE IS 'Kode for de andre kriteriene oppgavene skal filtreres på';
COMMENT ON COLUMN OPPGAVE_EGENSKAP.KL_ANDRE_KRITERIER_TYPE IS 'Kodeverk andre kriterier';