INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE, GYLDIG_FOM, GYLDIG_TOM)
VALUES (seq_kodeliste.nextval, 'BEHANDLING_TYPE', 'BT-008', 'ae0046', 'Anke',
        to_date('01.07.2019', 'DD.MM.RRRR'), to_date('31.12.9999', 'DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN, OPPRETTET_AV, OPPRETTET_TID)
VALUES (seq_kodeliste.nextval, 'BEHANDLING_TYPE', 'BT-008', 'NB', 'Anke', 'VL', current_timestamp);