INSERT INTO KODEVERK (KODE, KODEVERK_EIER, NAVN, BESKRIVELSE, OPPRETTET_AV, SAMMENSATT)
VALUES ('OPPGAVE_EVENT_TYPE', 'VLLOS', 'OPPGAVE_EVENT_TYPE', 'Internt kodeverk for hva som har skjedd med oppgaver.','VLLOS', 'N');

INSERT INTO KODELISTE (id, kodeverk, kode, gyldig_fom)
VALUES  (seq_kodeliste.nextval, 'OPPGAVE_EVENT_TYPE', 'OPPRETTET', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE (id, kodeverk, kode, gyldig_fom)
VALUES  (seq_kodeliste.nextval, 'OPPGAVE_EVENT_TYPE', 'LUKKET', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE (id, kodeverk, kode, gyldig_fom)
VALUES  (seq_kodeliste.nextval, 'OPPGAVE_EVENT_TYPE', 'VENT', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE (id, kodeverk, kode, gyldig_fom)
VALUES  (seq_kodeliste.nextval, 'OPPGAVE_EVENT_TYPE', 'GJENAPNET', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (id, kl_kodeverk, kl_kode, sprak, navn)
VALUES  (seq_kodeliste.nextval, 'OPPGAVE_EVENT_TYPE', 'OPPRETTET', 'NB', 'Opprettet oppgave');

INSERT INTO KODELISTE_NAVN_I18N (id, kl_kodeverk, kl_kode, sprak, navn)
VALUES  (seq_kodeliste.nextval, 'OPPGAVE_EVENT_TYPE', 'LUKKET', 'NB', 'Lukket oppgave');

INSERT INTO KODELISTE_NAVN_I18N (id, kl_kodeverk, kl_kode, sprak, navn)
VALUES  (seq_kodeliste.nextval, 'OPPGAVE_EVENT_TYPE', 'VENT', 'NB', 'Lukket på grunn av satt på vent');

INSERT INTO KODELISTE_NAVN_I18N (id, kl_kodeverk, kl_kode, sprak, navn)
VALUES  (seq_kodeliste.nextval, 'OPPGAVE_EVENT_TYPE', 'GJENAPNET', 'NB', 'Lukket på grunn av satt på vent');

CREATE TABLE OPPGAVE_EVENT_LOGG (
   ID NUMBER(19,0) NOT NULL
  ,BEHANDLING_ID NUMBER(19,0) NOT NULL
  ,EVENT_TYPE VARCHAR2(100 CHAR) NOT NULL
  ,ANDRE_KRITERIER_TYPE VARCHAR2(100 CHAR)
  ,KL_ANDRE_KRITERIER_TYPE VARCHAR2(100 CHAR) AS ('ANDRE_KRITERIER') NOT NULL
  ,KL_EVENT_TYPE VARCHAR2(100 CHAR) AS ('OPPGAVE_EVENT_TYPE') NOT NULL,
   versjon            NUMBER(19, 0) DEFAULT 0           NOT NULL,
   opprettet_av       VARCHAR2(20 CHAR) DEFAULT 'VLLOS'    NOT NULL,
   opprettet_tid      TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
   endret_av          VARCHAR2(20 CHAR),
   endret_tid         TIMESTAMP(3)
  ,CONSTRAINT PK_OPPGAVE_EVENT_TYPE PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_OPPGAVE_EVENT_LOGG MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_OPPGAVE_EVENT_LOGG_1 on OPPGAVE_EVENT_LOGG(BEHANDLING_ID);

CREATE INDEX IDX_OPPGAVE_EVENT_LOGG_2 on OPPGAVE_EVENT_LOGG(EVENT_TYPE);

CREATE INDEX IDX_OPPGAVE_EVENT_LOGG_3 on OPPGAVE_EVENT_LOGG(ANDRE_KRITERIER_TYPE);

ALTER TABLE OPPGAVE_EVENT_LOGG ADD CONSTRAINT FK_OPPGAVE_EVENT_LOGG_1
FOREIGN KEY (KL_EVENT_TYPE, EVENT_TYPE) REFERENCES KODELISTE (kodeverk, kode);

ALTER TABLE OPPGAVE_EVENT_LOGG ADD CONSTRAINT FK_OPPGAVE_EVENT_LOGG_2
FOREIGN KEY (KL_ANDRE_KRITERIER_TYPE, ANDRE_KRITERIER_TYPE) REFERENCES KODELISTE (kodeverk, kode);

COMMENT ON TABLE OPPGAVE_EVENT_LOGG is 'Eventlogg for alt som gjøres med oppgaver';

COMMENT ON COLUMN OPPGAVE_EVENT_LOGG.ID IS 'PK';
COMMENT ON COLUMN OPPGAVE_EVENT_LOGG.BEHANDLING_ID IS 'Behandlingen det er koblet til';
COMMENT ON COLUMN OPPGAVE_EVENT_LOGG.EVENT_TYPE IS 'Typen event';
COMMENT ON COLUMN OPPGAVE_EVENT_LOGG.ANDRE_KRITERIER_TYPE IS 'Spesialkriterier som påvirker åpning og lukking av oppgaver';