ALTER TABLE OPPGAVE_EGENSKAP ADD SISTE_SAKSBEHANDLER_FOR_TOTR  VARCHAR2(20 CHAR);

COMMENT ON COLUMN OPPGAVE_EGENSKAP.SISTE_SAKSBEHANDLER_FOR_TOTR IS 'Saksbehandleren som sendte behandlingen til totrinnskontroll';