ALTER SEQUENCE SEQ_OPPGAVE_FILTRERING INCREMENT BY 200;

INSERT INTO OPPGAVE_FILTRERING (ID, NAVN, SORTERING, AVDELING_ID)
VALUES (SEQ_OPPGAVE_FILTRERING.nextval,'Frist', 'BEHFRIST',-1);

INSERT INTO OPPGAVE_FILTRERING (ID, NAVN, SORTERING, AVDELING_ID)
VALUES (SEQ_OPPGAVE_FILTRERING.nextval,'Opprettet', 'OPPRBEH',-1);

