ALTER TABLE RESERVASJON ADD FLYTTET_AV VARCHAR2(100 CHAR);
COMMENT ON COLUMN RESERVASJON.FLYTTET_AV IS 'Ident som har flyttet reservasjonen';

ALTER TABLE RESERVASJON ADD FLYTTET_TIDSPUNKT TIMESTAMP(3);
COMMENT ON COLUMN RESERVASJON.FLYTTET_TIDSPUNKT IS 'Tidspunkt for flytting av reservasjonen';

ALTER TABLE RESERVASJON ADD BEGRUNNELSE VARCHAR2(500 CHAR);
COMMENT ON COLUMN RESERVASJON.BEGRUNNELSE IS 'Begrunnelse for opphør/flytting av reservasjon';