CREATE TABLE RESERVASJON_EVENT_LOGG (
   ID NUMBER(19,0) NOT NULL
  ,RESERVASJON_ID NUMBER(19,0) NOT NULL
  ,OPPGAVE_ID NUMBER(19,0) NOT NULL
  ,RESERVERT_TIL TIMESTAMP(3)
  ,RESERVERT_AV VARCHAR2(20 CHAR)
  ,FLYTTET_AV VARCHAR2(100 CHAR)
  ,FLYTTET_TIDSPUNKT TIMESTAMP(3)
  ,BEGRUNNELSE VARCHAR2(500 CHAR),
   versjon            NUMBER(19, 0) DEFAULT 0           NOT NULL,
   opprettet_av       VARCHAR2(20 CHAR) DEFAULT 'VLLOS'    NOT NULL,
   opprettet_tid      TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
   endret_av          VARCHAR2(20 CHAR),
   endret_tid         TIMESTAMP(3)
  ,CONSTRAINT PK_RESERVASJON_EVENT_LOGG PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_RESERVASJON_EVENT_LOGG MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_RESERVASJON_EVENT_LOGG_1 on RESERVASJON_EVENT_LOGG(RESERVASJON_ID);

CREATE INDEX IDX_RESERVASJON_EVENT_LOGG_2 on RESERVASJON_EVENT_LOGG(OPPGAVE_ID);

COMMENT ON TABLE RESERVASJON_EVENT_LOGG is 'Eventlogg for alt som gjøres med reservasjoner';

COMMENT ON COLUMN RESERVASJON_EVENT_LOGG.ID IS 'PK';
COMMENT ON COLUMN RESERVASJON_EVENT_LOGG.RESERVASJON_ID IS 'Id for reservasjonen';
COMMENT ON COLUMN RESERVASJON_EVENT_LOGG.OPPGAVE_ID IS 'Oppgaven det er koblet til';
COMMENT ON COLUMN RESERVASJON_EVENT_LOGG.RESERVERT_TIL IS 'Tidspunkt for hvor lenge reservasjonen er gyldig';
COMMENT ON COLUMN RESERVASJON_EVENT_LOGG.RESERVERT_AV IS 'Ident for hvem oppgaven er reservert på';
COMMENT ON COLUMN RESERVASJON_EVENT_LOGG.FLYTTET_AV IS 'Ident for hvem som evt. har flyttet reservasjonen';
COMMENT ON COLUMN RESERVASJON_EVENT_LOGG.FLYTTET_TIDSPUNKT IS 'Tidspunkt reservasjonen evt. er flyttet';
COMMENT ON COLUMN RESERVASJON_EVENT_LOGG.BEGRUNNELSE IS 'Begrunnelse for flytting/frigjøring av reservasjon';
