ALTER TABLE OPPGAVE ADD UTFORT_FRA_ADMIN VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
COMMENT ON COLUMN OPPGAVE.UTFORT_FRA_ADMIN IS 'Settes til true når Oppgave er endret fra admin-tjeneste';

ALTER TABLE OPPGAVE ADD OPPGAVE_AVSLUTTET TIMESTAMP(3);
COMMENT ON COLUMN OPPGAVE.OPPGAVE_AVSLUTTET IS 'Tidspunkt for avslutting av Oppgave';