INSERT INTO AVDELING(ID, AVDELING_ENHET,NAVN) values (-1, '4406','NAV Familie- og pensjonsytelser Drammen');
INSERT INTO AVDELING(ID, AVDELING_ENHET,NAVN) values (-2, '4842','NAV Familie- og pensjonsytelser Stord');

ALTER TABLE OPPGAVE_FILTRERING ADD CONSTRAINT FK_LISTE_1 FOREIGN KEY (AVDELING_ID) REFERENCES AVDELING;