CREATE TABLE AVDELING_SAKSBEHANDLER (
  SAKSBEHANDLER_ID NUMBER(19, 0) NOT NULL,
  AVDELING_ID      NUMBER(19, 0) NOT NULL,
  CONSTRAINT PK_AVDELING_SAKSBEHANDLER PRIMARY KEY (SAKSBEHANDLER_ID, AVDELING_ID),
  CONSTRAINT FK_AVDELING_SAKSBEHANDLER_1 FOREIGN KEY (SAKSBEHANDLER_ID) REFERENCES SAKSBEHANDLER(ID),
  CONSTRAINT FK_AVDELING_SAKSBEHANDLER_2 FOREIGN KEY (AVDELING_ID) REFERENCES AVDELING(ID)
);

CREATE INDEX IDX_AVDELING_SAKSBEHANDLER_1 on AVDELING_SAKSBEHANDLER(SAKSBEHANDLER_ID);
CREATE INDEX IDX_AVDELING_SAKSBEHANDLER_2 on AVDELING_SAKSBEHANDLER(AVDELING_ID);

COMMENT ON TABLE AVDELING_SAKSBEHANDLER is 'Tabell som er koblingen mellom avdeling og saksbehandler';

COMMENT ON COLUMN AVDELING_SAKSBEHANDLER.SAKSBEHANDLER_ID IS 'FK til saksbehandler';
COMMENT ON COLUMN AVDELING_SAKSBEHANDLER.AVDELING_ID IS 'FK til avdeling';