DROP INDEX IDX_OPPGAVE_EGENSKAP_1;
CREATE INDEX IDX_OPPGAVE_EGENSKAP_1 on OPPGAVE_EGENSKAP(OPPGAVE_ID);

ALTER TABLE OPPGAVE_EGENSKAP ADD CONSTRAINT FK_OPPGAVE_EGENSKAP_2 FOREIGN KEY (OPPGAVE_ID) REFERENCES OPPGAVE(ID);

CREATE INDEX IDX_OPPGAVE_5 on OPPGAVE(BEHANDLINGSFRIST);
CREATE INDEX IDX_OPPGAVE_6 on OPPGAVE(BEHANDLING_OPPRETTET);
CREATE INDEX IDX_OPPGAVE_7 on OPPGAVE(FORSTE_STONADSDAG);
