ALTER TABLE FILTRERING_ANDRE_KRITERIER ADD INKLUDER VARCHAR2(1 CHAR) DEFAULT 'J';

UPDATE FILTRERING_ANDRE_KRITERIER SET FILTRERING_ANDRE_KRITERIER.INKLUDER = 'J';

ALTER TABLE FILTRERING_ANDRE_KRITERIER MODIFY (INKLUDER NOT NULL ENABLE);

COMMENT ON COLUMN FILTRERING_ANDRE_KRITERIER.INKLUDER IS 'Verdi som sier om det skal filtreres inn eller filtreres vekk.';
