CREATE TABLE OPPGAVE_FILTRERING(
  ID NUMBER(19,0) NOT NULL
  ,NAVN VARCHAR2(100 CHAR) NOT NULL
  ,SORTERING VARCHAR2(100 CHAR) NOT NULL
  ,KL_SORTERING VARCHAR2(100 CHAR) AS ('KO_SORTERING') NOT NULL
  ,AVDELING_ID NUMBER(19,0) NOT NULL,
   versjon            NUMBER(19, 0) DEFAULT 0           NOT NULL,
   opprettet_av       VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
   opprettet_tid      TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
   endret_av          VARCHAR2(20 CHAR),
   endret_tid         TIMESTAMP(3)
  ,CONSTRAINT PK_OPPGAVE_FILTRERING PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_OPPGAVE_FILTRERING MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_OPPGAVE_FILTRERING_1 on OPPGAVE_FILTRERING(AVDELING_ID);

COMMENT ON TABLE OPPGAVE_FILTRERING is 'Tabell som skal inneholde informasjon om lister som brukes til filtrering av oppgaver';

COMMENT ON COLUMN OPPGAVE_FILTRERING.ID IS 'PK';
COMMENT ON COLUMN OPPGAVE_FILTRERING.NAVN IS 'Navn på listen';
COMMENT ON COLUMN OPPGAVE_FILTRERING.SORTERING IS 'Hva skal listen sorteres på';
COMMENT ON COLUMN OPPGAVE_FILTRERING.KL_SORTERING IS 'Kodeverk sorteringstype';
COMMENT ON COLUMN OPPGAVE_FILTRERING.AVDELING_ID IS 'Avdelingsenhet oppgavefiltreringa er koblet til';