INSERT INTO KODEVERK (KODE, KODEVERK_EIER, NAVN, BESKRIVELSE, OPPRETTET_AV, SAMMENSATT)
VALUES ('EVENTMOTTAK_STATUS', 'VLLOS', 'EVENTMOTTAK_STATUS', 'Internt kodeverk for status på eventmottak.','VLLOS', 'N');

INSERT INTO KODELISTE (id, kodeverk, kode, gyldig_fom)
VALUES  (seq_kodeliste.nextval, 'EVENTMOTTAK_STATUS', 'FEILET', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE (id, kodeverk, kode, gyldig_fom)
VALUES  (seq_kodeliste.nextval, 'EVENTMOTTAK_STATUS', 'FERDIG', to_date('2000-01-01', 'YYYY-MM-DD'));


INSERT INTO KODELISTE_NAVN_I18N (id, kl_kodeverk, kl_kode, sprak, navn)
VALUES  (seq_kodeliste.nextval, 'EVENTMOTTAK_STATUS', 'FEILET', 'NB', 'Feilet');

INSERT INTO KODELISTE_NAVN_I18N (id, kl_kodeverk, kl_kode, sprak, navn)
VALUES  (seq_kodeliste.nextval, 'EVENTMOTTAK_STATUS', 'FERDIG', 'NB', 'Ferdig lagt inn.');

CREATE TABLE EVENTMOTTAK_FEILLOGG (
   ID NUMBER(19,0) NOT NULL
  ,MELDING CLOB NOT NULL
  ,STATUS VARCHAR2(100 CHAR) NOT NULL
  ,ANTALL_FEILEDE_FORSOK NUMBER(19,0) DEFAULT 0
  ,SISTE_KJORING_TS TIMESTAMP(3)
  ,FEILMELDING_SISTE_KJORING CLOB
  ,KL_STATUS VARCHAR2(100 CHAR) AS ('EVENTMOTTAK_STATUS') NOT NULL,
   versjon            NUMBER(19, 0) DEFAULT 0           NOT NULL,
   opprettet_av       VARCHAR2(20 CHAR) DEFAULT 'VLLOS'    NOT NULL,
   opprettet_tid      TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
   endret_av          VARCHAR2(20 CHAR),
   endret_tid         TIMESTAMP(3)
  ,CONSTRAINT PK_EVENTMOTTAK_FEILLOGG PRIMARY KEY (ID)
);


CREATE SEQUENCE SEQ_EVENTMOTTAK_FEILLOGG MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_EVENTMOTTAK_FEILLOGG_1 on EVENTMOTTAK_FEILLOGG(STATUS);

CREATE INDEX IDX_EVENTMOTTAK_FEILLOGG_2 on EVENTMOTTAK_FEILLOGG(SISTE_KJORING_TS);

ALTER TABLE EVENTMOTTAK_FEILLOGG ADD CONSTRAINT FK_EVENTMOTTAK_FEILLOGG_1
FOREIGN KEY (KL_STATUS, STATUS) REFERENCES KODELISTE (kodeverk, kode);

COMMENT ON TABLE EVENTMOTTAK_FEILLOGG is 'Feillogg for eventer som kommer fra fpsak';

COMMENT ON COLUMN EVENTMOTTAK_FEILLOGG.ID IS 'PK';
COMMENT ON COLUMN EVENTMOTTAK_FEILLOGG.MELDING IS 'Meldingen som kom fra eventkøen';
COMMENT ON COLUMN EVENTMOTTAK_FEILLOGG.STATUS IS 'Status for meldingen';
COMMENT ON COLUMN EVENTMOTTAK_FEILLOGG.ANTALL_FEILEDE_FORSOK IS 'Antallet feilede forsøk';
COMMENT ON COLUMN EVENTMOTTAK_FEILLOGG.SISTE_KJORING_TS IS 'Tidspunkt for siste kjøring';
COMMENT ON COLUMN EVENTMOTTAK_FEILLOGG.FEILMELDING_SISTE_KJORING IS 'Feilmelding for siste kjøring';