CREATE TABLE SAKSBEHANDLER (
   ID NUMBER(19,0) NOT NULL
  ,SAKSBEHANDLER_IDENT VARCHAR2(20 CHAR) NOT NULL,
   versjon            NUMBER(19, 0) DEFAULT 0           NOT NULL,
   opprettet_av       VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
   opprettet_tid      TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
   endret_av          VARCHAR2(20 CHAR),
   endret_tid         TIMESTAMP(3)
  ,CONSTRAINT PK_SAKSBEHANDLER PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_SAKSBEHANDLER MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_SAKSBEHANDLER_1 on SAKSBEHANDLER(SAKSBEHANDLER_IDENT);

COMMENT ON TABLE SAKSBEHANDLER is 'Tabell som inneholder saksbehandleren som kan løse oppgaver';

COMMENT ON COLUMN SAKSBEHANDLER.ID IS 'PK';
COMMENT ON COLUMN SAKSBEHANDLER.SAKSBEHANDLER_IDENT IS 'Saksbehandlerident';


CREATE TABLE AVDELING (
   ID NUMBER(19,0) NOT NULL,
   AVDELING_ENHET VARCHAR2(10 CHAR) NOT NULL,
   NAVN VARCHAR2(255 CHAR) NOT NULL,
   versjon            NUMBER(19, 0) DEFAULT 0           NOT NULL,
   opprettet_av       VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
   opprettet_tid      TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
   endret_av          VARCHAR2(20 CHAR),
   endret_tid         TIMESTAMP(3)
  ,CONSTRAINT PK_AVDELING PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_AVDELING MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_AVDELING_1 on AVDELING(AVDELING_ENHET);

COMMENT ON TABLE AVDELING is 'Tabell som inneholder avdelingene som kan utføre oppgaver';

COMMENT ON COLUMN AVDELING.ID IS 'PK';
COMMENT ON COLUMN AVDELING.AVDELING_ENHET IS 'Identifikasjon på enhet som har oppgaver.';