ALTER TABLE OPPGAVE_FILTRERING ADD ER_DYNAMISK_PERIODE VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
COMMENT ON COLUMN OPPGAVE_FILTRERING.ER_DYNAMISK_PERIODE IS 'Angir om intervallet for perioden er dynamisk satt';

ALTER TABLE OPPGAVE_FILTRERING ADD FOM_DATO date;
COMMENT ON COLUMN OPPGAVE_FILTRERING.FOM_DATO IS 'Datointervall fra og med dato';

ALTER TABLE OPPGAVE_FILTRERING ADD TOM_DATO date;
COMMENT ON COLUMN OPPGAVE_FILTRERING.TOM_DATO IS 'Datointervall til og med dato';

ALTER TABLE OPPGAVE_FILTRERING ADD FOM_DAGER NUMBER(19,0);
COMMENT ON COLUMN OPPGAVE_FILTRERING.FOM_DAGER IS 'Datointervall fra og med dag';

ALTER TABLE OPPGAVE_FILTRERING ADD TOM_DAGER NUMBER(19,0);
COMMENT ON COLUMN OPPGAVE_FILTRERING.TOM_DAGER IS 'Datointervall til og med dag';