ALTER TABLE SAKSBEHANDLER ADD (
    NAVN VARCHAR2(250 char),
    ANSATT_ENHET VARCHAR2(20 char)
);
COMMENT ON COLUMN SAKSBEHANDLER.NAVN IS 'Saksbehandlers navn';
COMMENT ON COLUMN SAKSBEHANDLER.ANSATT_ENHET IS 'Enhet der saksbehandler er ansatt';
