ALTER TABLE "OPPGAVE" MODIFY EKSTERN_ID VARCHAR(36 CHAR) NOT NULL ENABLE;

ALTER TABLE "OPPGAVE_EVENT_LOGG" MODIFY EKSTERN_ID VARCHAR(36 CHAR) NOT NULL ENABLE;

CREATE INDEX "IDX_OPPGAVE_EVENT_LOGG_1" ON "OPPGAVE_EVENT_LOGG" ("EKSTERN_ID");
