update OPPGAVE set BEHANDLING_ID = EKSTERN_ID;
update OPPGAVE_EVENT_LOGG set BEHANDLING_ID = EKSTERN_ID;

alter table OPPGAVE MODIFY BEHANDLING_ID RAW(16) NOT NULL;
alter table OPPGAVE_EVENT_LOGG MODIFY BEHANDLING_ID RAW(16) NOT NULL;
