CREATE TABLE "EKSTERN_IDENTIFIKATOR"
    (	"ID" NUMBER(19,0) NOT NULL,
	    "SYSTEM" VARCHAR2(100 CHAR) NOT NULL,
	    "EKSTERN_REF_ID" VARCHAR(36 CHAR) NOT NULL,
        "OPPRETTET_AV" VARCHAR2(20 CHAR) DEFAULT 'VLLOS' NOT NULL,
	    "OPPRETTET_TID" TIMESTAMP (3) DEFAULT systimestamp NOT NULL,
	    "ENDRET_AV" VARCHAR2(20 CHAR),
	    "ENDRET_TID" TIMESTAMP (3)
    );
    COMMENT ON TABLE "EKSTERN_IDENTIFIKATOR"  IS 'Tabell som mapper identifikatorer fra eksterne systemer til en unik intern id';
    COMMENT ON COLUMN "EKSTERN_IDENTIFIKATOR"."ID" IS 'PK. Identifikator som benyttes internt i FPLOS';
    COMMENT ON COLUMN "EKSTERN_IDENTIFIKATOR"."SYSTEM" IS 'Det ekstere systemet';
    COMMENT ON COLUMN "EKSTERN_IDENTIFIKATOR"."EKSTERN_REF_ID" IS 'Identifikator som det ekstere systemet benytter for saken eller behandlingen. Benyttes til oppslag.';

    CREATE UNIQUE INDEX "PK_EKSTERN_IDENTIFIKATOR" ON "EKSTERN_IDENTIFIKATOR" ("ID");

    ALTER TABLE "EKSTERN_IDENTIFIKATOR" ADD CONSTRAINT "PK_EKSTERN_IDENTIFIKATOR" PRIMARY KEY ("ID")
        USING INDEX  ENABLE;

    ALTER TABLE "EKSTERN_IDENTIFIKATOR" ADD CONSTRAINT "UIDX_EXTERNAL_SYSTEM" UNIQUE ("SYSTEM", "EKSTERN_REF_ID");

    CREATE SEQUENCE  "SEQ_EKSTERN_IDENTIFIKATOR"  MINVALUE 1 INCREMENT BY 50 START WITH 1 NOCACHE  ORDER  NOCYCLE ;

    ALTER TABLE "OPPGAVE" MODIFY (
        EKSTERN_ID NUMBER(19,0)
    );

    ALTER TABLE "OPPGAVE" ADD CONSTRAINT "FK_OPPGAVE_EKSTERN_ID" FOREIGN KEY ("EKSTERN_ID")
	    REFERENCES "EKSTERN_IDENTIFIKATOR" ("ID") ENABLE;

    CREATE INDEX "IDX_OPPGAVE_8" ON "OPPGAVE" ("EKSTERN_ID");

	ALTER TABLE "OPPGAVE_EVENT_LOGG" ADD "EKSTERN_ID" NUMBER(19,0);

	COMMENT ON COLUMN "OPPGAVE"."EKSTERN_ID" IS 'Ekstern ID som identifiserer behandling i fagsystem.';

	ALTER TABLE "OPPGAVE_EVENT_LOGG" ADD CONSTRAINT "FK_OPPGAVE_EVENT_EKSTERN_ID" FOREIGN KEY ("EKSTERN_ID")
	    REFERENCES "EKSTERN_IDENTIFIKATOR" ("ID") ENABLE;

    CREATE INDEX "IDX_OPPGAVE_EVENT_LOGG_4" ON "OPPGAVE_EVENT_LOGG" ("EKSTERN_ID");


