ALTER TABLE "KONFIG_VERDI" DROP CONSTRAINT "FK_KONFIG_VERDI_1";
ALTER TABLE "KONFIG_VERDI" DROP CONSTRAINT "PK_KONFIG_VERDI";
ALTER TABLE "KONFIG_VERDI_KODE" DROP CONSTRAINT "FK_KONFIG_VERDI_KODE_1";
ALTER TABLE "KONFIG_VERDI_KODE" DROP CONSTRAINT "FK_KONFIG_VERDI_KODE_2";
ALTER TABLE "KONFIG_VERDI_KODE" DROP CONSTRAINT "PK_KONFIG_VERDI_KODE";
ALTER TABLE "KONFIG_VERDI_TYPE" DROP CONSTRAINT "PK_KONFIG_VERDI_TYPE";
ALTER TABLE "KONFIG_VERDI_GRUPPE" DROP CONSTRAINT "PK_KONFIG_VERDI_GRUPPE";

DROP INDEX "IDX_KONFIG_VERDI_KODE_6";
DROP INDEX "IDX_KONFIG_VERDI_KODE_7";
DROP INDEX "IDX_KONFIG_VERDI_1";
DROP INDEX "IDX_KONFIG_VERDI_2";
DROP INDEX "IDX_KONFIG_VERDI_3";

DROP INDEX "PK_KONFIG_VERDI";
DROP INDEX "PK_KONFIG_VERDI_GRUPPE";
DROP INDEX "PK_KONFIG_VERDI_KODE";
DROP INDEX "PK_KONFIG_VERDI_TYPE";
DROP INDEX "UIDX_KONFIG_VERDI_1";
DROP INDEX "UIDX_KONFIG_VERDI_2";

DROP SEQUENCE "SEQ_KONFIG_VERDI";

DROP TABLE "KONFIG_VERDI";
DROP TABLE "KONFIG_VERDI_KODE";
DROP TABLE "KONFIG_VERDI_TYPE";
DROP TABLE "KONFIG_VERDI_GRUPPE";
