ALTER TABLE "OPPGAVE_EVENT_LOGG" ADD "BEHANDLING_ID" RAW(16);
COMMENT ON COLUMN "OPPGAVE_EVENT_LOGG"."BEHANDLING_ID" IS 'Behandling id for behandling i fagsystem.';

ALTER TABLE "OPPGAVE" ADD "BEHANDLING_ID" RAW(16);
COMMENT ON COLUMN "OPPGAVE"."BEHANDLING_ID" IS 'Behandling id for behandling i fagsystem.';
