ALTER TABLE FILTRERING_YTELSE_TYPE DROP CONSTRAINT FK_FILTRERING_YTELSE_TYPE_1;
ALTER TABLE FILTRERING_YTELSE_TYPE DROP COLUMN KL_FAGSAK_YTELSE_TYPE;

ALTER TABLE OPPGAVE DROP CONSTRAINT FK_OPPGAVE_2;
ALTER TABLE OPPGAVE DROP COLUMN KL_FAGSAK_YTELSE_TYPE;
