ALTER TABLE "EVENTMOTTAK_FEILLOGG" DROP CONSTRAINT "FK_EVENTMOTTAK_FEILLOGG_1";
ALTER TABLE "FILTRERING_BEHANDLING_TYPE" DROP CONSTRAINT "FK_FILTR_BEHANDLING_TYPE_1";
ALTER TABLE "KODELISTE" DROP CONSTRAINT "FK_KODELISTE_01";
ALTER TABLE "KODELISTE_NAVN_I18N" DROP CONSTRAINT "FK_KODELISTE_02";
ALTER TABLE "KODELISTE" DROP CONSTRAINT "CHK_UNIQUE_KODELISTE";

ALTER TABLE "EVENTMOTTAK_FEILLOGG" DROP COLUMN "ANTALL_FEILEDE_FORSOK";
ALTER TABLE "EVENTMOTTAK_FEILLOGG" DROP COLUMN "SISTE_KJORING_TS";
ALTER TABLE "EVENTMOTTAK_FEILLOGG" DROP COLUMN "KL_STATUS";

DROP TABLE "KODELISTE_NAVN_I18N";
DROP TABLE "KODELISTE";
DROP TABLE "KODEVERK";

UPDATE "OPPGAVE_EVENT_LOGG"
SET "ANDRE_KRITERIER_TYPE" = null
WHERE "ANDRE_KRITERIER_TYPE" = '-';
