const behandlingType = {
  FORSTEGANGSSOKNAD: 'BT-002',
  REVURDERING: 'BT-004',
  KLAGE: 'BT-003',
  ANKE: 'BT-008',
  DOKUMENTINNSYN: 'BT-006',
  TILBAKEBETALING: 'BT-007',
  TILBAKEBETALING_REVURDERING: 'BT-009',
};

export default behandlingType;
