enum KoSortering {
  OPPRETT_BEHANDLING = 'OPPRBEH',
  BEHANDLINGSFRIST = 'BEHFRIST',
  BELOP = 'BELOP',
  FEILUTBETALINGSTART = 'FEILUTBETALINGSTART',
  FORSTE_STONADSDAG = 'FORSTONAD',
};

export default KoSortering;
