CREATE TABLE SAKSBEHANDLER_GRUPPE
(
    ID            NUMBER(19)                             NOT NULL
        CONSTRAINT PK_SAKSBEHANDLER_GRUPPE PRIMARY KEY,
    GRUPPE_NAVN   VARCHAR2(255 char)                     NOT NULL,
    AVDELING_ID   NUMBER(19)                             NOT NULL
        CONSTRAINT FK_SAKSBEHANDLER_GRUPPE_AVDELING_01 REFERENCES AVDELING (ID),
    VERSJON       NUMBER(19)        default 0            not null,
    OPPRETTET_AV  VARCHAR2(20 char) default 'VL'         not null,
    OPPRETTET_TID TIMESTAMP(3)      default systimestamp not null,
    ENDRET_AV     VARCHAR2(20 char),
    ENDRET_TID    TIMESTAMP(3)
);

CREATE INDEX IDX_SAKSBEHANDLER_GRUPPE_1
    on SAKSBEHANDLER_GRUPPE (AVDELING_ID);

COMMENT ON TABLE SAKSBEHANDLER_GRUPPE IS 'Tabell som holder informasjon om grupper';
COMMENT ON column SAKSBEHANDLER_GRUPPE.ID IS 'Gruppe ID';
COMMENT ON column SAKSBEHANDLER_GRUPPE.GRUPPE_NAVN IS 'Gruppenavn';
COMMENT ON column SAKSBEHANDLER_GRUPPE.AVDELING_ID IS 'Referanse til avdeling som gruppen tilhører';
COMMENT ON column SAKSBEHANDLER_GRUPPE.VERSJON IS 'angir versjon for optimistisk låsing hvor aktuelt';
COMMENT ON column SAKSBEHANDLER_GRUPPE.OPPRETTET_AV IS 'Bruker som opprettet raden';
COMMENT ON column SAKSBEHANDLER_GRUPPE.OPPRETTET_TID IS 'Tidspunkt for opprettelse';
COMMENT ON column SAKSBEHANDLER_GRUPPE.ENDRET_AV IS 'Endret av';
COMMENT ON column SAKSBEHANDLER_GRUPPE.ENDRET_TID IS 'Timestamp endring';


CREATE TABLE GRUPPE_TILKNYTNING
(
    SAKSBEHANDLER_ID NUMBER(19) NOT NULL
        CONSTRAINT FK_GRUPPE_TILKNYTNING_SAKSBEHANDLER_01 REFERENCES SAKSBEHANDLER (ID),
    GRUPPE_ID        NUMBER(19) NOT NULL
        CONSTRAINT FK_GRUPPE_TILKNYTNING_SAKSBEHANDLER_GRUPPE_01 REFERENCES SAKSBEHANDLER_GRUPPE (ID),
    CONSTRAINT PK_GRUPPE_TILKNYTNING PRIMARY KEY (SAKSBEHANDLER_ID, GRUPPE_ID)
);

CREATE SEQUENCE SEQ_GRUPPE START WITH 1000 INCREMENT BY 50 NOCACHE;

CREATE INDEX IDX_GRUPPE_TILKNYTNING_1
    on GRUPPE_TILKNYTNING (SAKSBEHANDLER_ID);

CREATE INDEX IDX_GRUPPE_TILKNYTNING_2
    on GRUPPE_TILKNYTNING (GRUPPE_ID);

COMMENT ON TABLE GRUPPE_TILKNYTNING IS 'Jointabell som holder koblinger mellom saksbehandlere og gruppe';
COMMENT ON column GRUPPE_TILKNYTNING.SAKSBEHANDLER_ID IS 'Saksbehandler ID';
COMMENT ON column GRUPPE_TILKNYTNING.GRUPPE_ID IS 'Gruppe ID';
