name: Bygg PR eller branches

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'

env:
  READER_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Sette opp Node
        uses: actions/setup-node@v3
        with:
          node-version: 17.8.0
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Hent og start Oracle image
        id: oracle
        run: |
          echo "Henter og starter Oracle image"
          cd .oracle
          docker-compose up --quiet-pull > nohup.out 2>&1 &
          sh -c 'tail -n +0 -f nohup.out | { sed "/Database opened./q" && kill $$; }' || true

      - name: Set build version
        run: |
          echo "BUILD_VERSION=2.8.2-$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV


      - name: Kompiler
        run: mvn install -q -B -s .github/.m2/settings.xml -Drevision=$BUILD_VERSION
        env:
          TZ: Europe/Oslo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
