name: Snyk vulnerabilities scanning of dependencies
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Sette opp Node
        uses: actions/setup-node@v3
        with:
          node-version: 17.8.0
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'

      - uses: snyk/actions/setup@master

      - name: Setup maven
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "github", "name": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
          servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.READER_TOKEN }}" }]'
          output_file: settings.xml

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Hent og start Oracle image
        run: |
          echo "Henter og starter Oracle image"
          cd .oracle
          docker-compose up --quiet-pull > nohup.out 2>&1 &
          sh -c 'tail -n +0 -f nohup.out | { sed "/Database opened./q" && kill $$; }' || true

      - name: Build
        run: |
          echo "Building snyk-snapshot"
          mvn -B -s settings.xml versions:set -DnewVersion=snyk-snapshot
          mvn install -q -B -s settings.xml -DskipTests
        env:
          READER_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Run Snyk monitor
        run: >
          snyk monitor
          --org=teamforeldrepenger
          --all-projects
          --configuration-attributes=usage:java-runtime
          --remote-repo-url=https://github.com/${{ github.repository }}.git
          -- -s settings.xml
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
